name: Flutter CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Run Automated Tests
      run: flutter test

    # 📦 Membangun APK Release dengan parameter UAS milikmu
    - name: Build APK Production
      run: flutter build apk --dart-define=ENV_NAME=PROD --dart-define=NAMA_DEPAN=Fitri --dart-define=NIM_ANDA=20123020 --release

    # 📤 Mengunggah file APK langsung ke halaman GitHub Actions Artifacts (Aman & Pasti Lolos)
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: uas-app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk